import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readdirSync,
	writeFileSync,
} from "node:fs";
import { createInterface } from "node:readline";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import chalk from "chalk";
import ora from "ora";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

function ask(query: string, options: string[]): Promise<string> {
	if (!process.stdin.isTTY) return Promise.resolve(options[0]);
	const rl = createInterface({ input: process.stdin, output: process.stdout });
	return new Promise((resolve) => {
		const formatted = `${chalk.cyan(query)} ${options.map((o) => chalk.gray(`(${o})`)).join(" ")}\n> `;
		rl.question(formatted, (answer) => {
			rl.close();
			const trimmed = answer.trim().toLowerCase();
			if (trimmed && options.some((o) => o.toLowerCase().startsWith(trimmed))) {
				resolve(options.find((o) => o.toLowerCase().startsWith(trimmed))!);
			} else if (trimmed && options.includes(trimmed)) {
				resolve(trimmed);
			} else {
				resolve(options[0]);
			}
		});
	});
}

function adaptConfig(projectType: string): string {
	let config: Record<string, { severity: string; minChars?: number; maxDays?: number; blacklist?: string[] }> = {
		"conteudo-minimo": { severity: "warning", minChars: 50 },
		"consistencia-terminologia": { severity: "warning" },
		"detecao-tom": { severity: "warning", blacklist: ["tipo", "tá", "pra", "blz", "kkk", "eita", "oi", "oi pessoal"] },
		"drift-temporal": { severity: "warning", maxDays: 30 },
		"secoes-vazias": { severity: "warning" },
		"acs-sem-metrica": { severity: "warning" },
		"baixa-confianca": { severity: "warning" },
	};

	if (projectType === "library") {
		config["detecao-tom"] = { severity: "off" };
		config["drift-temporal"] = { severity: "warning", maxDays: 60 };
	} else if (projectType === "mobile") {
		config["drift-temporal"] = { severity: "error", maxDays: 14 };
		config["baixa-confianca"] = { severity: "error" };
	} else if (projectType === "cli") {
		config["detecao-tom"] = { severity: "off" };
	}

	return JSON.stringify({ heuristics: config }, null, 2);
}

function adaptersForTool(tool: string): string[] {
	const all = ["cursor", "claude-code", "windsurf", "vscode", "opencode"];
	if (tool === "todos") return all;
	const map: Record<string, string[]> = {
		opencode: ["opencode"],
		cursor: ["cursor"],
		windsurf: ["windsurf"],
		"claude code": ["claude-code"],
		"vscode copilot": ["vscode"],
	};
	return map[tool.toLowerCase()] || all;
}

function generateAdapterFiles(root: string, tools: string[]) {
	const adapters: Array<{ path: string; content: string }> = [];

	const baseContent = (name: string, format: "at" | "text") => `# Letra Context — ${name} Adapter
# Generated by letra init. Do not edit manually.

${format === "at" ? "# Context\n@.letra/context.md\n@.letra/constitution.md\n@.letra/glossary.md\n@.letra/focus.md\n" : `Read the following files before starting any task:
- .letra/context.md
- .letra/constitution.md
- .letra/glossary.md
- .letra/focus.md (if exists, defines current session focus)
`}
# Rules
- Always read specs in .letra/specs/ before writing code
- Run \`letra validate\` to check acceptance criteria
- Follow the constitution.md rules strictly
- Use formal tone in all generated content
`;

	for (const tool of tools) {
		switch (tool) {
			case "cursor":
				adapters.push({ path: join(root, ".cursorrules"), content: baseContent("Cursor", "at") });
				break;
			case "claude-code":
				adapters.push({ path: join(root, "CLAUDE.md"), content: baseContent("Claude Code", "text") });
				break;
			case "windsurf":
				adapters.push({ path: join(root, ".windsurfrules"), content: baseContent("Windsurf", "at") });
				break;
			case "vscode":
				adapters.push({ path: join(root, ".github", "copilot-instructions.md"), content: baseContent("VSCode Copilot", "text") });
				break;
			case "opencode":
				adapters.push({ path: join(root, "AGENTS.md"), content: baseContent("OpenCode", "text") });
				break;
		}
	}

	for (const { path, content } of adapters) {
		const dir = join(path, "..");
		if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
		writeFileSync(path, content);
		console.log(`    ${chalk.gray("Created")} ${path.replace(root + "/", "")}`);
	}
}

export async function init(targetPath?: string, options?: { yes?: boolean }) {
	const root = resolve(process.cwd(), targetPath || ".");
	const letraDir = join(root, ".letra");

	const spinner = ora("Initializing Letra...").start();

	if (existsSync(letraDir)) {
		spinner.warn(chalk.yellow(".letra/ already exists"));
		return;
	}

	try {
		let projectType = "web-app";
		let tool = "cursor";

		if (options?.yes || !process.stdin.isTTY) {
			projectType = "web-app";
			tool = "todos";
		} else {
			spinner.stop();

			projectType = await ask("Project type?", ["web-app", "cli", "library", "mobile"]);
			const toolNames = ["Cursor", "Windsurf", "Claude Code", "VSCode Copilot", "OpenCode", "Todos"];
			const answer = await ask("AI coding agent?", toolNames);
			tool = answer.toLowerCase();

			spinner.start();
		}

		mkdirSync(join(letraDir, "decisions"), { recursive: true });
		mkdirSync(join(letraDir, "specs", "_template"), { recursive: true });
		mkdirSync(join(letraDir, "adapters"), { recursive: true });

		const templateDir = join(__dirname, "..", "..", ".letra");
		const templates = [
			"context.md",
			"constitution.md",
			"glossary.md",
			"lessons-learned.md",
		];
		for (const file of templates) {
			const src = join(templateDir, file);
			const dest = join(letraDir, file);
			if (existsSync(src)) copyFileSync(src, dest);
		}

		const specTemplate = join(letraDir, "specs", "_template.md");
		const specContent = `# Spec Template

## Outcome
O que o usuário consegue fazer quando isso estiver pronto.

## Constraints
Limitações técnicas e de negócio que não podem ser violadas.

## Exclusions
O que explicitamente NÃO está neste escopo.

## Acceptance Criteria
- [ ] **Critério 1**: Descrição binária (passa/falha).

## Context
Por que estamos construindo isso.
`;
		writeFileSync(specTemplate, specContent);

		const configPath = join(letraDir, "config.json");
		writeFileSync(configPath, adaptConfig(projectType));
		console.log(`    ${chalk.gray("Created")} .letra/config.json`);

		const tools = adaptersForTool(tool);
		generateAdapterFiles(root, tools);

		if (tool === "todos" || tool === "vscode") {
			const vscodeDir = join(root, ".vscode");
			if (!existsSync(vscodeDir)) mkdirSync(vscodeDir, { recursive: true });
			const vscodeSettingsPath = join(vscodeDir, "settings.json");
			const vscodeSettingsContent = `{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit"
  },
  "files.autoSave": "onFocusChange"
}
`;
			writeFileSync(vscodeSettingsPath, vscodeSettingsContent);
			console.log(`    ${chalk.gray("Created")} .vscode/settings.json`);
		}

		spinner.succeed(chalk.green(".letra/ initialized successfully"));
		console.log("");
		console.log("  Next steps:");
		console.log(
			`    ${chalk.cyan("letra spec new <name>")}  Create your first spec`,
		);
		console.log(`    ${chalk.cyan("letra lint")}             Validate specs`);
	} catch (error) {
		spinner.fail(chalk.red("Failed to initialize Letra"));
		process.exit(1);
	}
}
