import { useEffect, useState } from "react";
import type { AgentIdentity, AgentSkill } from "@letra/types";
import { AgentAvatar, Badge, Button, Card, CardContent, Input, Textarea } from "@letra/ui";

const empty: AgentIdentity = { id: "", displayName: "", role: "implementer", bio: "", avatar: { type: "initials", value: "AG" }, color: "oklch(0.7 0.12 280)", skills: [], status: "offline", stageBindings: [], adapterHints: {} };
export default function AgentsView() {
	const [agents, setAgents] = useState<AgentIdentity[]>([]); const [draft, setDraft] = useState<AgentIdentity | null>(null);
	const load = () => fetch("/api/agents").then((r) => r.json()).then((d) => Array.isArray(d) && setAgents(d)).catch(() => {});
	useEffect(() => { load(); }, []);
	function editSkills(value: string) { setDraft((d) => d ? { ...d, skills: value.split(",").map((label): AgentSkill => ({ id: label.trim().toLowerCase().replace(/\s+/g, "-"), label: label.trim(), level: "intermediate" })).filter((skill) => skill.label) } : d); }
	async function save() { if (!draft?.id || !draft.displayName) return; const exists = agents.some((a) => a.id === draft.id); await fetch(exists ? `/api/agents/${encodeURIComponent(draft.id)}` : "/api/agents", { method: exists ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); setDraft(null); load(); }
	return <div className="grid gap-6 p-6"><div className="flex items-center justify-between"><div><h1 className="text-xl font-semibold">Equipe de agentes</h1><p className="text-sm text-[var(--color-text-secondary)]">Identidades, skills e status do harness.</p></div><Button onClick={() => setDraft({ ...empty, id: `agent-${Date.now()}` })}>Novo agente</Button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{agents.map((agent) => <Card key={agent.id}><CardContent className="gap-3 p-4"><div className="flex items-center gap-3"><AgentAvatar agent={agent} /><div className="min-w-0"><p className="font-semibold">{agent.displayName}</p><p className="text-xs text-[var(--color-text-secondary)]">{agent.role} · {agent.status}</p></div><Button size="sm" variant="ghost" onClick={() => setDraft({ ...agent })}>Editar</Button></div><p className="text-sm text-[var(--color-text-secondary)]">{agent.bio}</p><div className="flex flex-wrap gap-1">{agent.skills.map((skill) => <Badge key={skill.id} variant="info" tone="soft">{skill.label} · {skill.level}</Badge>)}</div></CardContent></Card>)}</div>{draft && <div className="grid max-w-xl gap-3 rounded-lg border border-border p-4"><h2 className="font-semibold">{agents.some((a) => a.id === draft.id) ? "Editar agente" : "Novo agente"}</h2><Input value={draft.displayName} placeholder="Nome" onChange={(e) => setDraft({ ...draft, displayName: e.target.value })} /><Input value={draft.role} placeholder="Role" onChange={(e) => setDraft({ ...draft, role: e.target.value })} /><Textarea value={draft.bio ?? ""} placeholder="Bio" onChange={(e) => setDraft({ ...draft, bio: e.target.value })} /><div className="flex gap-2"><Button onClick={save}>Salvar</Button><Button variant="ghost" onClick={() => setDraft(null)}>Cancelar</Button></div></div>}</div>;
}
