import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it } from "vitest";
import {
	analyzeWorkspaceSetup,
	captureWorkspaceSetup,
	planWorkspaceSetup,
	restoreWorkspaceSetup,
	rollbackWorkspaceSetup,
	saveWorkspaceSetupManifest,
} from "./workspace.js";

const roots: string[] = [];

function tempRoot() {
	const root = mkdtempSync(join(tmpdir(), "letra-smart-setup-"));
	roots.push(root);
	return root;
}

afterEach(() => {
	for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe("workspace smart setup", () => {
	it("detects locations, stack and only preselects evidenced adapters", () => {
		const root = tempRoot();
		const frontend = join(root, "apps", "frontend");
		mkdirSync(join(frontend, ".opencode"), { recursive: true });
		writeFileSync(
			join(frontend, "package.json"),
			JSON.stringify({
				name: "@acme/frontend",
				dependencies: { react: "19.0.0", vite: "6.0.0" },
				devDependencies: { typescript: "5.0.0" },
			}),
		);
		writeFileSync(join(frontend, ".opencode", "instructions.md"), "# existing");
		writeFileSync(join(frontend, "AGENTS.md"), "# existing");
		mkdirSync(join(frontend, ".codex"), { recursive: true });
		writeFileSync(join(frontend, ".codex", "config.toml"), "[mcp_servers.letra]");

		const proposal = analyzeWorkspaceSetup({ name: "Acme", root });

		expect(proposal.locations).toHaveLength(1);
		expect(proposal.locations[0]).toMatchObject({
			label: "frontend",
			stack: expect.arrayContaining(["Node.js", "React", "Vite", "TypeScript"]),
		});
		expect(
			proposal.locations[0].adapters.find((adapter) => adapter.tool === "opencode"),
		).toMatchObject({
			state: "detected",
			selected: true,
		});
		expect(
			proposal.locations[0].adapters.find((adapter) => adapter.tool === "cursor"),
		).toMatchObject({
			state: "available",
			selected: false,
		});
		expect(
			proposal.locations[0].adapters.find((adapter) => adapter.tool === "codex"),
		).toMatchObject({
			label: "Codex",
			state: "detected",
			selected: true,
			evidence: [".codex/config.toml"],
			capabilities: expect.objectContaining({
				mcp: true,
				liveContext: "mcp",
			}),
		});
	});

	it("classifies new, generated and unknown adapter files without overwriting conflicts", () => {
		const root = tempRoot();
		const target = join(root, "frontend");
		mkdirSync(target);
		writeFileSync(
			join(target, "CLAUDE.md"),
			"# Generated by letra init. Do not edit manually.",
		);
		writeFileSync(join(target, ".cursorrules"), "# Team-owned rules");

		const plan = planWorkspaceSetup({
			proposalId: "proposal-1",
			workspaceRoot: root,
			targets: [
				{
					id: "frontend",
					label: "Frontend",
					path: target,
					adapters: ["claude-code", "cursor", "hermes"],
				},
			],
		});

		expect(plan.operations).toEqual(
			expect.arrayContaining([
				expect.objectContaining({
					kind: "update",
					path: expect.stringContaining("CLAUDE.md"),
					diff: expect.stringContaining("+ # Letra Context"),
				}),
				expect.objectContaining({
					kind: "conflict",
					path: expect.stringContaining(".cursorrules"),
					diff: expect.stringContaining("- # Team-owned rules"),
				}),
				expect.objectContaining({
					kind: "create",
					path: expect.stringContaining(".hermes/instructions.md"),
					diff: expect.stringContaining("+ # Generated by letra init"),
				}),
			]),
		);
		expect(plan.conflictCount).toBe(1);
	});

	it("preserves user Codex settings while managing the Letra MCP section", () => {
		const root = tempRoot();
		const target = join(root, "frontend");
		mkdirSync(join(target, ".codex"), { recursive: true });
		writeFileSync(join(target, ".codex", "config.toml"), 'model = "gpt-team"\n');

		const plan = planWorkspaceSetup({
			proposalId: "proposal-codex",
			workspaceRoot: root,
			targets: [
				{
					id: "frontend",
					label: "Frontend",
					path: target,
					adapters: ["codex"],
				},
			],
		});

		const config = plan.operations.find(
			(operation) => operation.artifactId === "codex-project-config",
		);
		expect(config).toMatchObject({
			kind: "update",
			tool: "codex",
			before: 'model = "gpt-team"\n',
			reason: "Seção MCP do Letra mesclada preservando a configuração do usuário.",
		});
		expect(config?.after).toContain('model = "gpt-team"');
		expect(config?.after).toContain("[mcp_servers.letra]");
		expect(plan.conflictCount).toBe(0);
	});

	it("rejects a manually added target that does not exist", () => {
		const root = tempRoot();
		expect(() =>
			planWorkspaceSetup({
				proposalId: "proposal-2",
				workspaceRoot: root,
				targets: [
					{
						id: "missing",
						label: "Missing",
						path: join(root, "missing"),
						adapters: ["cursor"],
					},
				],
			}),
		).toThrow("não existe");
	});

	it("captures changes and restores them directly or from a rollback manifest", () => {
		const root = tempRoot();
		const target = join(root, "frontend");
		mkdirSync(target);
		const existing = join(target, "CLAUDE.md");
		const created = join(target, ".cursorrules");
		writeFileSync(existing, "# Generated by letra init. Do not edit manually.\nold");
		const plan = planWorkspaceSetup({
			proposalId: "proposal-rollback",
			workspaceRoot: root,
			targets: [
				{
					id: "frontend",
					label: "Frontend",
					path: target,
					adapters: ["claude-code", "cursor"],
				},
			],
		});
		const snapshots = captureWorkspaceSetup(plan);
		writeFileSync(existing, "new");
		writeFileSync(created, "created");

		restoreWorkspaceSetup(snapshots);
		expect(readText(existing)).toContain("old");
		expect(() => readText(created)).toThrow();

		writeFileSync(existing, "new-again");
		writeFileSync(created, "created-again");
		const manifestId = saveWorkspaceSetupManifest(
			root,
			plan.proposalId,
			plan.operations,
			snapshots,
		);
		rollbackWorkspaceSetup(root, manifestId);
		expect(readText(existing)).toContain("old");
		expect(() => readText(created)).toThrow();
	});
});

function readText(path: string) {
	return readFileSync(path, "utf-8");
}
