import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";
import { buildHarnessSnapshot } from "./builder.js";
import { formatAdapterContent } from "./formatters.js";
import type { AdapterSource, GenerateOptions } from "./types.js";

const ADAPTER_HEADER: Record<AdapterSource, string> = {
	init: "# Generated by letra init. Do not edit manually.\n",
	"flow-move": "# Gerado por letra flow move. Nao edite manualmente.\n",
	focus: "# Gerado por letra focus. Nao edite manualmente.\n",
};

const TOOL_TARGETS: Record<string, { paths: string[]; format: "at" | "text"; displayName: string }> = {
	cursor: { paths: [".cursorrules"], format: "at", displayName: "Cursor" },
	"claude-code": { paths: ["CLAUDE.md"], format: "text", displayName: "Claude Code" },
	windsurf: { paths: [".windsurfrules"], format: "at", displayName: "Windsurf" },
	vscode: {
		paths: [".github/copilot-instructions.md"],
		format: "text",
		displayName: "VSCode Copilot",
	},
	opencode: { paths: [".opencode/instructions.md", "AGENTS.md"], format: "text", displayName: "OpenCode" },
	hermes: { paths: [".hermes/instructions.md"], format: "text", displayName: "Hermes Agent" },
};

export interface GenerateAdaptersOptions extends GenerateOptions {
	quiet?: boolean;
	verb?: "Created" | "Updated";
}

export function generateAdapters(
	root: string,
	tools: string[],
	options: GenerateAdaptersOptions,
): void {
	const snapshot = buildHarnessSnapshot(root, options);
	let header = ADAPTER_HEADER[options.source];
	const verb = options.verb ?? (options.source === "init" ? "Created" : "Updated");

	if (options.graveIssueCount && options.graveIssueCount > 0) {
		const warn = `\n### ⚠ ATENÇÃO: ${options.graveIssueCount} problema(s) grave(s) detectado(s) pelo diagnóstico automático\nExecute \`letra health\` para detalhes e \`letra health ack <id>\` para reconhecer.\n`;
		header += warn;
	}

	for (const tool of tools) {
		const target = TOOL_TARGETS[tool];
		if (!target) continue;

		const content = formatAdapterContent(snapshot, target.format, {
			source: options.source,
			displayName: target.displayName,
		});

		for (const path of target.paths) {
			const filePath = join(root, path);
			const dir = join(filePath, "..");
			if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
			writeFileSync(filePath, header + content);

			if (!options.quiet) {
				console.log(
					`  ${chalk.gray(verb)} ${path}`,
				);
			}
		}
	}
}
