import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";
import { buildHarnessSnapshot } from "./builder.js";
import { formatAdapterContent } from "./formatters.js";
import type { AdapterSource, GenerateOptions } from "./types.js";

const ADAPTER_HEADER: Record<AdapterSource, string> = {
	init: "# Generated by letra init. Do not edit manually.\n",
	"flow-move": "# Gerado por letra flow move. Nao edite manualmente.\n",
	focus: "# Gerado por letra focus. Nao edite manualmente.\n",
};

const TOOL_TARGETS: Record<
	string,
	{ path: string; format: "at" | "text"; displayName: string }
> = {
	cursor: { path: ".cursorrules", format: "at", displayName: "Cursor" },
	"claude-code": { path: "CLAUDE.md", format: "text", displayName: "Claude Code" },
	windsurf: { path: ".windsurfrules", format: "at", displayName: "Windsurf" },
	vscode: {
		path: ".github/copilot-instructions.md",
		format: "text",
		displayName: "VSCode Copilot",
	},
	opencode: { path: "AGENTS.md", format: "text", displayName: "OpenCode" },
};

export interface GenerateAdaptersOptions extends GenerateOptions {
	quiet?: boolean;
	verb?: "Created" | "Updated";
}

export function generateAdapters(
	root: string,
	tools: string[],
	options: GenerateAdaptersOptions,
): void {
	const snapshot = buildHarnessSnapshot(root, options);
	const header = ADAPTER_HEADER[options.source];
	const verb = options.verb ?? (options.source === "init" ? "Created" : "Updated");

	for (const tool of tools) {
		const target = TOOL_TARGETS[tool];
		if (!target) continue;

		const content = formatAdapterContent(snapshot, target.format, {
			source: options.source,
			displayName: target.displayName,
		});

		const filePath = join(root, target.path);
		const dir = join(filePath, "..");
		if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
		writeFileSync(filePath, header + content);

		if (!options.quiet) {
			console.log(`  ${chalk.gray(verb)} ${filePath.replace(`${root}/`, "").replace(`${root}\\`, "")}`);
		}
	}
}
